name: Operator Hacker
accent: "#FF6B00"
cursor: "#FF6B00"
background:
  top: "#002733"
  bottom: "#000000"
foreground: "#ABB2BF"
details: darker
terminal_colors:
  normal:
    black: "#0B0F14"
    red: "#E06C75"
    green: "#98C379"
    yellow: "#FF6B00"
    blue: "#4B8FCC"
    magenta: "#6D5BD0"
    cyan: "#56B6C2"
    white: "#ABB2BF"
  bright:
    black: "#5C6370"
    red: "#E06C75"
    green: "#98C379"
    yellow: "#FFB000"
    blue: "#4B8FCC"
    magenta: "#6D5BD0"
    cyan: "#56B6C2"
    white: "#FFFFFF"
