name: Operator Hacker
accent: "#FF5F00"
cursor: "#FF5F00"
background: "#21252B"
foreground: "#ABB2BF"
details: darker
terminal_colors:
  normal:
    black: "#21252B"
    red: "#E06C75"
    green: "#98C379"
    yellow: "#FF5F00"
    blue: "#4B8FCC"
    magenta: "#C678DD"
    cyan: "#56B6C2"
    white: "#ABB2BF"
  bright:
    black: "#5C6370"
    red: "#E06C75"
    green: "#98C379"
    yellow: "#FFB000"
    blue: "#4B8FCC"
    magenta: "#C678DD"
    cyan: "#56B6C2"
    white: "#FFFFFF"
