gui:
  nerdFontsVersion: "3"
  showIcons: true
  showRandomTip: false
  showCommandLog: false
  filterMode: fuzzy
git:
  paging:
    colorArg: always
    pager: less -FRX
  autoFetch: false
  autoRefresh: true
  parseEmoji: true
confirmOnQuit: false
quitOnTopLevelReturn: false
disableStartupPopups: true
promptToReturnFromSubprocess: false
