gui:
  nerdFontsVersion: "3"
  showIcons: true
  showRandomTip: false
  showCommandLog: false
  filterMode: fuzzy
git:
  diffRenderers:
    - colorArg: always
      command: less -FRX
  autoFetch: false
  autoRefresh: true
  parseEmoji: true
confirmOnQuit: false
quitOnTopLevelReturn: false
disableStartupPopups: true
promptToReturnFromSubprocess: false
